stages:
- test

semgrep:
  stage: test
  script:
    - docker run -e d57592bde84d566f083bf5cce6840b66e0a3c93f57a0f0a85ed1074693c5b8f0 --rm -v "${PWD}:/src" semgrep/semgrep semgrep ci
  variables:
    SEMGREP_APP_TOKEN: "d57592bde84d566f083bf5cce6840b66e0a3c93f57a0f0a85ed1074693c5b8f0"
    SAST_EXCLUDED_PATHS: "node_modules,dist,build,tests,coverage"
    SEARCH_MAX_DEPTH: 40
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  allow_failure: true
  tags:
    - default_runner
