variables:
  STAGING_ENABLED: "false"
  PRODUCTION_ENABLED: "false"
  DAST_DISABLED: "true"
  AUTO_DEVOPS_BUILD_IMAGE_ENABLED: "false"
  AUTO_DEVOPS_BUILD_ENABLED: "false"
  REVIEW_DISABLED: "true"
  AUTO_DEVOPS_DEPLOY_ENABLED: "false"
  CODE_QUALITY_DISABLED: "true"
  LICENSE_MANAGEMENT_DISABLED: "true"
  PERFORMANCE_DISABLED: "true"
  CANARY_ENABLED: "false"

stages:
- build
- test

sast:
  stage: test

include:
- template: Auto-DevOps.gitlab-ci.yml
