stages:
- test

include:
  - template: Security/SAST.gitlab-ci.yml

sast:
  stage: test
  image:
    name: registry.gitlab.com/gitlab-org/security-products/analyzers/semgrep:5
    entrypoint: [""]
  script:
    - /analyzer run
  variables:
    SAST_EXCLUDED_PATHS: "node_modules,dist,build,tests,coverage"
    SEARCH_MAX_DEPTH: 20
    SAST_EXCLUDED_ANALYZERS: "bandit-sast,eslint-sast,nodejs-scan-sast"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  allow_failure: true
  tags:
    - default_runner
  artifacts:
    reports:
      sast: gl-sast-report.html
