stages:
- test

include:
  - template: Security/SAST.gitlab-ci.yml

sast:
  stage: test
  script:
    - /analyzer run
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"  # 只在合并请求时触发
      when: always
    - when: never  # 其他情况下不触发
