variables:
  STAGING_ENABLED: "false"
  PRODUCTION_ENABLED: "false"
  DAST_DISABLED: "true"
  AUTO_DEVOPS_BUILD_IMAGE_ENABLED: "false"
  AUTO_DEVOPS_BUILD_ENABLED: "false"

stages:
- build
- test
#- deploy
#- review
#- dast
#- staging
#- canary
#- production
#- incremental rollout 10%
#- incremental rollout 25%
#- incremental rollout 50%
#- incremental rollout 100%
#- performance
#- cleanup
sast:
  stage: test
include:
- template: Auto-DevOps.gitlab-ci.yml
