stages:
- test

variables:
  STAGING_ENABLED: "false"
  PRODUCTION_ENABLED: "false"
  DAST_DISABLED: "true"
  AUTO_DEVOPS_BUILD_IMAGE_ENABLED: "false"
  AUTO_DEVOPS_BUILD_ENABLED: "false"
  REVIEW_DISABLED: "true"
  AUTO_DEVOPS_DEPLOY_ENABLED: "false"
  CODE_QUALITY_DISABLED: "true"
  LICENSE_MANAGEMENT_DISABLED: "true"
  PERFORMANCE_DISABLED: "true"
  CANARY_ENABLED: "false"

include:
  - template: Security/SAST.gitlab-ci.yml

sast:
  stage: test
  script:
    - /analyzer run
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"  # 只在合并请求时触发
      when: always
    - when: never  # 其他情况下不触发
